import {Customers} from '../model/customer';

export const customerDao: Customers[] = [
  {
    id: 1,
    name: 'Viet',
    birthday: 10,
    gender: 'Nam',
    card: 1234,
    phone: 12121212,
    email: 'viet@gmail.com',
    address: 'Quang Nam',
    type: 'Vip',
  },
  {
    id: 2,
    name: 'Tan',
    birthday: 10,
    gender: 'Nam',
    card: 1234,
    phone: 12121212,
    email: 'tan@gmail.com',
    address: 'Da Nang',
    type: 'Vip',
  },
  {
    id: 3,
    name: 'Tu',
    birthday: 10,
    gender: 'Nam',
    card: 1234,
    phone: 12121212,
    email: 'tu@gmail.com',
    address: 'Hue',
    type: 'Vip',
  },
  {
    id: 4,
    name: 'Anh',
    birthday: 10,
    gender: 'Nam',
    card: 1234,
    phone: 12121212,
    email: 'anh@gmail.com',
    address: 'Nghe An',
    type: 'Vip',
  },
  {
    id: 5,
    name: 'Long',
    birthday: 10,
    gender: 'Nam',
    card: 1234,
    phone: 12121212,
    email: 'long@gmail.com',
    address: 'Ha Noi',
    type: 'Vip',
  }
];

